# Netlify configuration pour React
[build]
  command = "npm run build"
  publish = "build"

# Redirections pour React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité et SEO
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Robots-Tag = "index, follow"

# Headers pour le sitemap (CRITIQUE pour Google)
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Robots-Tag = "noindex"

# Headers pour robots.txt
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"